[services]
  [services.1]
  name="mqtt_handler"
  addr="0.0.0.0:1883 mqtt"
  [services.2]
  name="barrage_handler"
  addr="0.0.0.0:8080 barrage"

[engine]
srvworker=10000
srvqueue=100000
ioworker=10000
ioqueue=100000
matrixbucket=16
matrixsize=524288
