[services]
#[services.1]
  #name="mqtt_handler"
  #addr="0.0.0.0:1883 mqtt"
  [services.2]
  name="barrage_handler"
  addr="0.0.0.0:8081 barrage"
  [services.3]
  name="http_handler"
  addr="0.0.0.0:8080 http"
  [services.4]
  name="ping_handler"
  addr="0.0.0.0:18080 ping"

[engine]
srvworker=1
srvqueue=1
ioworker=1
ioqueue=1
matrixbucket=16
matrixsize=1024
#524288

[http]
localaddr="0.0.0.0:7172"
remoteaddr="172.16.6.10:8998"

[zk]
addrs = ["172.16.6.74"]
timeout = "500ms"
srvid = "1"
