[services]
  #[services.1]
  #name="mqtt_handler"
  #addr="0.0.0.0:1883 mqtt"
  [services.2]
  name="barrage_handler"
  addr="0.0.0.0:8081 barrage"

[engine]
srvworker=10000
srvqueue=100000
ioworker=10000
ioqueue=100000
matrixbucket=16
matrixsize=1024
#524288

[http]
localaddr="0.0.0.0:7172"
remoteaddr="172.16.6.135:8998"
